apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: helloworld
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  entrypoint: hello-word
  arguments:
    parameters:
    - name: coolname
      value: "erfaedsfds"
  templates:
  - name: hello-word
    container:
      image: vizgen/hello_word
      env:
        - name: COOL_NAME
          value: "{{workflow.parameters.coolname}}"
