apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  entrypoint: dagger
  templates:

    - name: hello-word
      container:
        image: vizgen/hello
        imagePullPolicy: Always
        env:
          - name: COOL_NAME
            value: "FRANKFURT"

    - name: on-error
      container:
        image: alpine:latest
        args: [sh, -c, "echo hello-word job has failed. This is a substitute job"]

    - dag:
        tasks:
          - name: hello-word
            template: hello-word
          - name: on-error
            template: on-error
            depends: "hello-word.Failed || hello-word.Errored"
      name: dagger

