apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-word-app
  annotations:
#    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/ignore-sync-condition: Extra
spec:
  entrypoint: hello-word
  arguments:
    parameters:
    - name: coolname
      value: "xxx"
  syncPolicy:
    automated:
      prune: true
#    syncOptions:
#      - Replace=true
  templates:
  - name: hello-word
    container:
      image: vizgen/hello_word
      imagePullPolicy: Always
      env:
        - name: COOL_NAME
          value: "{{workflow.parameters.coolname}}"

