apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-word-cron
  annotations:
#    argocd.argoproj.io/sync-options: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
#    argocd.argoproj.io/ignore-sync-condition: Extra
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    workflowTemplateRef:
      name: hello-template
