apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-word
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/ignore-sync-condition: Extra
spec:
  entrypoint: hello-word
  arguments:
    parameters:
    - name: coolname
      value: "XAX"
  templates:
  - name: hello-word
    container:
      image: vizgen/hello_word
      env:
        - name: COOL_NAME
          value: "{{workflow.parameters.coolname}}"
      
