apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dhello-
  annotations:
    argocd.argoproj.io/hook: PreSync
#:q
spec:
  entrypoint: hello-word
  arguments:
    parameters:
    - name: coolname
      value: "deli"
  templates:
  - name: hello-word
    container:
      image: vizgen/hello_word
      env:
        - name: COOL_NAME
          value: "{{workflow.parameters.coolname}}"
