apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-word-app
#  annotations:
#    argocd.argoproj.io/sync-options: PreSync
##    argocd.argoproj.io/hook-delete-policy: HookS
#    argocd.argoproj.io/ignore-sync-condition: Extra
spec:
  entrypoint: hello-word
  arguments:
    parameters:
    - name: coolname
      value: "cccc"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
  templates:
  - name: hello-word
    container:
      image: vizgen/hello_word
      imagePullPolicy: Always
      env:
        - name: COOL_NAME
          value: "{{workflow.parameters.coolname}}"

