apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-word-cron
#  annotations:
#    argocd.argoproj.io/sync-options: PostSync
#    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
#    argocd.argoproj.io/ignore-sync-condition: Extra
#    argocd.argoproj.io/sync-options: PruneLast=true
#    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  onExit: exit-handler
  workflowSpec:
    entrypoint: hello-word
    arguments:
      parameters:
      - name: coolname
        value: "000"
    templates:
    - name: hello-word
      container:
        image: vizgen/hello_word
        imagePullPolicy: Always
        env:
          - name: COOL_NAME
            value: "{{workflow.parameters.coolname}}"

    - name: exit-handler
      steps:
      - - name: backoff
          template: backoff
#          when: "{{workflow.status}} != Succeeded"

    - name: backoff
      container:
         image: alpine:latest
         command: [sh, c]
         args: ["some other job"]

