apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL:  https://github.com/yavuzkaymak/argo-demo.git
    targetRevision: HEAD
    path: manifests/argo-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
