apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - Replace=true
    - PruneLast=true
    - allowEmpty=true
  source:
    repoURL:  https://github.com/yavuzkaymak/argo-demo.git
    targetRevision: HEAD
    path: manifests/argo-workflow/workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
