apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/ignore-sync-condition: Extra
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
  source:
    repoURL:  https://github.com/yavuzkaymak/argo-demo.git
    targetRevision: HEAD
    path: manifests/argo-workflow/workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
